# Generated by Django 4.2 on 2024-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='recap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
