# Generated by Django 4.2 on 2024-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_interview_date_remove_interview_recap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='interview',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='backend.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='backend.interview'),
        ),
    ]
